# Preprocesamiento de datos sobre desastres naturales en los a√±os 2016-2017-2018

 Fuente: https://public.emdat.be/

**1. Importamos la base de datos**

In [25]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/database_2010_2024.xlsx')

df.head()

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,...,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,2009-0595-IND,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,GLIDE:CW-2010-000013,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,71.563596,"[{""adm1_code"":1489,""adm1_name"":""Delhi""},{""adm1...",2010-08-04,2023-09-25
1,2010-0002-TJK,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,GLIDE:EQ-2010-000001,NaN,TJK,...,NaN,NaN,NaN,NaN,1500.0,2096.0,71.563596,"[{""adm2_code"":37581,""adm2_name"":""Vanchskiy""}]",2010-02-03,2023-09-25
2,2010-0003-SLB,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp000h5np,NaN,SLB,...,NaN,NaN,NaN,NaN,NaN,NaN,71.563596,"[{""adm2_code"":25652,""adm2_name"":""Administrativ...",2014-05-12,2023-09-25
3,2010-0004-BGD,No,tec-tra-roa-roa,Technological,Transport,Road,Road,NaN,NaN,BGD,...,NaN,NaN,NaN,NaN,NaN,NaN,71.563596,NaN,2010-01-05,2023-09-25
4,2010-0005-IND,No,tec-tra-rai-rai,Technological,Transport,Rail,Rail,NaN,NaN,IND,...,NaN,NaN,NaN,NaN,NaN,NaN,71.563596,NaN,2010-01-05,2023-09-25

**2. Apartamos las columnas que necesitamos.**

In [26]:
# Mantener solo las variables mencionadas a continuacion.

columns_to_keep = ['Start Year', 'Start Month', 'Start Day',
    'Country', 'Region', 'Location', 'Magnitude',
    "Disaster Subgroup", 'Total Damage (\'000 US$)', 'Total Deaths' ]
df = df[columns_to_keep]

# Mostramos los primeros 5 elementos para identificar que se realizo el primer Filtro
df.head()

,Start Year,Start Month,Start Day,Country,Region,Location,Magnitude,Disaster Subgroup,Total Damage ('000 US$),Total Deaths
0,2010,1.0,2.0,India,Asia,"Srinagar city ('72808' district, '40424' Jammu...",-9.0,Meteorological,NaN,100.0
1,2010,1.0,2.0,Tajikistan,Asia,"Uskrogh, Rogh, Payshanbeobod, Gishkhun, Dashti...",5.4,Geophysical,1500.0,NaN
2,2010,1.0,3.0,Solomon Islands,Oceania,Administrative unit not available,7.1,Geophysical,NaN,NaN
3,2010,1.0,1.0,Bangladesh,Asia,Kanaipur road,NaN,Transport,NaN,17.0
4,2010,1.0,2.0,India,Asia,NaN,NaN,Transport,NaN,10.0

**3. Filtramos los desastres hidrologicos**

In [27]:
df = df[df["Disaster Subgroup"] == "Hydrological"]

df.head()

,Start Year,Start Month,Start Day,Country,Region,Location,Magnitude,Disaster Subgroup,Total Damage ('000 US$),Total Deaths
6,2010,1.0,NaN,Burundi,Africa,"Gatumba village (Mutimbuzi district, Bujumbura...",NaN,Hydrological,NaN,NaN
8,2010,1.0,4.0,Pakistan,Asia,Administrative unit not available district (Ja...,NaN,Hydrological,18000.0,19.0
15,2010,1.0,14.0,Philippines,Asia,"Jabonga, Las Nieves, Santiago areas (Agusan de...",NaN,Hydrological,22.0,2.0
16,2010,1.0,18.0,Egypt,Africa,"El Arish 1 district (North Sinai province), Ra...",226100.0,Hydrological,NaN,12.0
17,2010,1.0,19.0,Israel,Asia,Southern District province,NaN,Hydrological,NaN,2.0

**4. Hacemos limpieza de los datos nulos eliminando las filas que contengan datos NaN en este caso en la columna magnitud.**

In [28]:
df = df.dropna(subset=['Magnitude'])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 506 entries, 16 to 7898
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Start Year               506 non-null    int64
 1   Start Month              506 non-null    float64
 2   Start Day                496 non-null    float64
 3   Country                  506 non-null    object
 4   Region                   506 non-null    object
 5   Location                 504 non-null    object
 6   Magnitude                506 non-null    float64
 7   Disaster Subgroup        506 non-null    object
 8   Total Damage ('000 US$)  196 non-null    float64
 9   Total Deaths             410 non-null    float64
dtypes: float64(5), int64(1), object(4)
memory usage: 43.5+ KB

**5. Con la siguiente funcion determinamos la limpieza que se realizo.**

In [29]:
df.isnull().sum()

Start Year                   0
Start Month                  0
Start Day                   10
Country                      0
Region                       0
Location                     2
Magnitude                    0
Disaster Subgroup            0
Total Damage ('000 US$)    310
Total Deaths                96
dtype: int64

**6. Para finalizar ajustamos el indice de manera organizada para tener coherencia en la data.**

In [30]:
indices = list(range(1,507))
df.index = indices
df.head()

,Start Year,Start Month,Start Day,Country,Region,Location,Magnitude,Disaster Subgroup,Total Damage ('000 US$),Total Deaths
1,2010,1.0,18.0,Egypt,Africa,"El Arish 1 district (North Sinai province), Ra...",226100.0,Hydrological,NaN,12.0
2,2010,1.0,1.0,Bolivia (Plurinational State of),Americas,"Beni, Chuquisaca, Cochabamba, La Paz and Santa...",102200.0,Hydrological,NaN,26.0
3,2010,1.0,11.0,Panama,Americas,"Bocas del Toro, Chiriqui, Vergaguas, Colon pro...",23340.0,Hydrological,NaN,NaN
4,2010,1.0,26.0,Mexico,Americas,"Distrito Federal, Mexico city, Michoacan provi...",122621.0,Hydrological,16000.0,41.0
5,2010,2.0,10.0,Peru,Americas,"La Esperanza, El Porvenir, Salaverry towns (Tr...",305800.0,Hydrological,NaN,20.0

**7.Guardamos el archivo de la data**

In [31]:
df.to_excel("/content/drive/MyDrive/Colab Notebooks/database_procesada_2010_2024.xlsx")